cache:
  auto_cleanup: true
  directory: null
  enabled: true
rofi:
  args: []
  max_lines: 15
  prompt: Commands
  use_markup: true
sources:
  directories:
  - ~/Veilcat-OSCP-Methodology
  file_patterns:
  - '*.md'
  - '*.markdown'
  files: []
  recursive: true
variables: {}
